### PR TITLE
Adding 2 new applications

### PR DESCRIPTION
**Pull request by deepthimk123**
1. Awards and Recognition App
2. Awards and Recognition Copilot

Both the apps having dependency on Awards and Recognition Base.

### CODE REVIEW

**Review by tverhasselt — APPROVED** [review]
approved

**Review by ankitchawla23 — APPROVED** [review]

**Review by ankitchawla23 — APPROVED** [review]
Approved

**Review by Ryanb58 — COMMENTED** [review]
LGTM

**Review by Ryanb58 — APPROVED** [review]
LGTM

**Comment by deepthimk123** [comment]
@microsoft-github-policy-service agree [company="{your company}"]

**Pull request merged**
